#!/bin/ksh
# ftd FastCGI form collector
#
# All configuration lives in /etc/ftd.conf, loaded by the daemon itself, so
# this script needs no environment handling. To run with an alternate
# configuration file (or any other daemon flag):
#
#	rcctl set ftd flags -c /etc/ftd2.conf
#
daemon="/usr/local/bin/ftd"
daemon_flags=${ftd_flags:-""}

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_cmd $1
